export const services = [
  {
    id: 1,
    name: { ar: 'نتفليكس بريميوم', en: 'Netflix Premium' },
    category: { ar: 'ترفيه', en: 'Entertainment' },
    amount: 56,
    currency: 'SAR',
    nextDate: getRelativeDate(3),
    billingCycle: { ar: 'شهري', en: 'Monthly' },
    startDate: '2023-04-01',
    website: 'https://netflix.com',
    status: 'active',
    riskLevel: 'low',
    priceChanged: false,
    unusedDays: 0,
    logo: 'N',
    color: '#E50914',
    decision: null,
    description: {
      ar: 'خدمة بث الأفلام والمسلسلات. الخطة الحالية تشمل 4 شاشات بجودة 4K.',
      en: 'Streaming service for movies and series. Current plan includes 4 screens in 4K quality.',
    },
    features: {
      ar: ['4 شاشات في وقت واحد', 'جودة 4K + HDR', 'تحميل للمشاهدة بدون إنترنت'],
      en: ['4 simultaneous screens', '4K + HDR quality', 'Downloads for offline viewing'],
    },
  },
  {
    id: 2,
    name: { ar: 'سبوتيفاي العائلية', en: 'Spotify Family' },
    category: { ar: 'موسيقى', en: 'Music' },
    amount: 32,
    currency: 'SAR',
    nextDate: getRelativeDate(7),
    billingCycle: { ar: 'شهري', en: 'Monthly' },
    startDate: '2023-08-15',
    website: 'https://spotify.com',
    status: 'active',
    riskLevel: 'low',
    priceChanged: false,
    unusedDays: 0,
    logo: 'S',
    color: '#1DB954',
    decision: null,
    description: {
      ar: 'خدمة الموسيقى العائلية تشمل حتى 6 حسابات مستقلة بدون إعلانات.',
      en: 'Family music plan with up to 6 independent accounts and no ads.',
    },
    features: {
      ar: ['6 حسابات مستقلة', 'بدون إعلانات', 'تحميل غير محدود'],
      en: ['6 independent accounts', 'No ads', 'Unlimited downloads'],
    },
  },
  {
    id: 3,
    name: { ar: 'شات جي بي تي بلاس', en: 'ChatGPT Plus' },
    category: { ar: 'إنتاجية', en: 'Productivity' },
    amount: 129,
    oldAmount: 75,
    currency: 'SAR',
    nextDate: getRelativeDate(1),
    billingCycle: { ar: 'شهري', en: 'Monthly' },
    startDate: '2024-01-10',
    website: 'https://chat.openai.com',
    status: 'needs_decision',
    riskLevel: 'high',
    priceChanged: true,
    unusedDays: 0,
    logo: 'G',
    color: '#10A37F',
    decision: null,
    description: {
      ar: 'الوصول لنماذج GPT-4 المتقدمة. ارتفع السعر من 75 إلى 129 ريال هذا الشهر.',
      en: 'Access to advanced GPT-4 models. Price jumped from SAR 75 to SAR 129 this month.',
    },
    features: {
      ar: ['وصول لـ GPT-4o', 'توليد صور بـ DALL·E', 'أولوية في الاستجابة'],
      en: ['Access to GPT-4o', 'Image generation with DALL·E', 'Priority response speed'],
    },
    reasons: {
      ar: [
        'ارتفع السعر بنسبة 72% مقارنة بالشهر الماضي',
        'تجاوز نسبة 32% من حدك الشهري',
        'يتجاوز متوسط إنفاقك على هذه الفئة بمقدار ضعفين',
      ],
      en: [
        'Price increased by 72% compared to last month',
        'Exceeds 32% of your monthly limit',
        'Double your average spending in this category',
      ],
    },
  },
  {
    id: 4,
    name: { ar: 'أدوبي كلاود الإبداعية', en: 'Adobe Creative Cloud' },
    category: { ar: 'تصميم', en: 'Design' },
    amount: 249,
    currency: 'SAR',
    nextDate: getRelativeDate(14),
    billingCycle: { ar: 'شهري', en: 'Monthly' },
    startDate: '2024-03-01',
    website: 'https://adobe.com',
    status: 'trial_ending',
    riskLevel: 'medium',
    priceChanged: false,
    unusedDays: 0,
    logo: 'A',
    color: '#FF0000',
    decision: null,
    trialEnding: true,
    description: {
      ar: 'باقة أدوبي الكاملة تشمل Photoshop وIllustrator وغيرها. الفترة التجريبية تنتهي قريباً.',
      en: 'Full Adobe suite including Photoshop, Illustrator and more. Trial period ending soon.',
    },
    features: {
      ar: ['Photoshop + Illustrator', 'Premiere Pro للفيديو', '100GB تخزين سحابي'],
      en: ['Photoshop + Illustrator', 'Premiere Pro for video', '100GB cloud storage'],
    },
  },
  {
    id: 5,
    name: { ar: 'كانفا برو', en: 'Canva Pro' },
    category: { ar: 'تصميم', en: 'Design' },
    amount: 42,
    currency: 'SAR',
    nextDate: getRelativeDate(21),
    billingCycle: { ar: 'شهري', en: 'Monthly' },
    startDate: '2023-11-20',
    website: 'https://canva.com',
    status: 'unused',
    riskLevel: 'medium',
    priceChanged: false,
    unusedDays: 45,
    logo: 'C',
    color: '#00C4CC',
    decision: null,
    description: {
      ar: 'أداة تصميم سهلة الاستخدام. لم تُستخدم منذ 45 يوماً — قد تحتاج لمراجعة.',
      en: 'Easy-to-use design tool. Not used for 45 days — may need review.',
    },
    features: {
      ar: ['قوالب احترافية', 'إزالة خلفية الصور', 'تصدير بدون علامة مائية'],
      en: ['Professional templates', 'Background removal', 'Export without watermark'],
    },
  },
]

export const cardInfo = {
  holderName: { ar: 'فجر الياتي', en: 'Fager Alyati' },
  lastFour: '4821',
  monthlyLimit: 400,
  usedAmount: 268,
  frozen: false,
}

export const bankMetrics = {
  totalSavingsPotential: 171,
  priceChangedCount: 2,
  unusedServicesCount: 1,
  riskScore: 68,
  merchants: [
    { name: { ar: 'أوبن إيه آي', en: 'OpenAI' }, changes: 3, changePercent: 72 },
    { name: { ar: 'أدوبي', en: 'Adobe' }, changes: 2, changePercent: 15 },
    { name: { ar: 'ميكروسوفت', en: 'Microsoft' }, changes: 1, changePercent: 8 },
    { name: { ar: 'سبوتيفاي', en: 'Spotify' }, changes: 1, changePercent: 5 },
  ],
  riskDistribution: [
    { label: { ar: 'منخفض', en: 'Low' }, value: 40, color: '#22c55e' },
    { label: { ar: 'متوسط', en: 'Medium' }, value: 35, color: '#f59e0b' },
    { label: { ar: 'مرتفع', en: 'High' }, value: 25, color: '#ef4444' },
  ],
}

function getRelativeDate(daysFromNow) {
  const d = new Date()
  d.setDate(d.getDate() + daysFromNow)
  return d.toISOString().split('T')[0]
}
